# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:

- checkout: self
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Tests'
    orchestratorConnection: 'TestUipathServiceConnection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'



- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'TestUipathServiceConnection'
    testProjectPath: '$(Build.SourcesDirectory)'
    environment: 'vopak_env'
    folderName: 'Default'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output'
  continueOnError: true
  
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'TestUipathServiceConnection'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Default'
    environments: 'vopak_env'

    
    
