# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:

- checkout: self
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Tests'
    orchestratorConnection: 'TurnKeyFeedyard'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'



- task: UiPathTest@2
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'TurnKeyFeedyard'
    testSet: 'Turnkey_TestSet'
    folderName: 'Default'
  continueOnError: true
  
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'TurnKeyFeedyard'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Default'
    environments: 'TurnKey_Env'

    
    
